'use client';

import { useState } from 'react';
import { Plus, FileText, Truck, Upload } from 'lucide-react';
import { Modal, PageTitle } from '../components/ui';
import { formatDate, formatMoney } from '../data/mock';

export default function PurchasesView({ purchases, onSave }) {
  const [form, setForm] = useState(null);
  const open = () => setForm({ supplier: '', date: new Date().toISOString().slice(0, 10), total: '', items: '', document: '' });
  const submit = async (event) => { event.preventDefault(); await onSave({ ...form, total: Number(form.total), items: Number(form.items) }); setForm(null); };
  return <><PageTitle eyebrow="Abastecimiento" title="Compras y boletas" description="Registra compras a proveedores y conserva el nombre del documento de sustento." action={<button className="btn-primary" onClick={open}><Plus size={18} /> Registrar compra</button>} /><section className="grid gap-4 lg:grid-cols-2">{purchases.map((purchase) => <article className="panel p-5" key={purchase.id}><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-amber/20 text-[#8c5c00]"><Truck size={20} /></span><span className="badge bg-black/5 text-black/45">{purchase.number}</span></div><h2 className="mt-5 text-lg font-black">{purchase.supplier}</h2><p className="mt-1 text-sm text-black/40">{formatDate(purchase.date)} · {purchase.items} unidades</p><div className="mt-5 flex items-center justify-between border-t border-black/5 pt-4"><div className="flex items-center gap-2 text-xs font-bold text-forest"><FileText size={16} />{purchase.document || 'Sin documento'}</div><strong>{formatMoney(purchase.total)}</strong></div></article>)}</section>{form && <Modal title="Registrar compra" onClose={() => setForm(null)}><form className="space-y-4" onSubmit={submit}><label className="block text-sm font-bold">Proveedor<input required className="field mt-2" value={form.supplier} onChange={(e) => setForm({ ...form, supplier: e.target.value })} /></label><div className="grid grid-cols-2 gap-4"><label className="text-sm font-bold">Fecha<input required type="date" className="field mt-2" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label><label className="text-sm font-bold">Unidades<input required min="1" type="number" className="field mt-2" value={form.items} onChange={(e) => setForm({ ...form, items: e.target.value })} /></label></div><label className="block text-sm font-bold">Total de compra<input required min="0" step="0.01" type="number" className="field mt-2" value={form.total} onChange={(e) => setForm({ ...form, total: e.target.value })} /></label><label className="block text-sm font-bold">Boleta, factura o foto<div className="mt-2 flex items-center gap-3 rounded-2xl border border-dashed border-black/15 bg-white p-4"><Upload className="text-forest" /><input type="file" accept="image/*,.pdf,.xml" onChange={(e) => setForm({ ...form, document: e.target.files?.[0]?.name || '' })} /></div></label><p className="text-xs text-black/40">En esta etapa se guarda el nombre del archivo. El almacenamiento real se conectará después.</p><button className="btn-primary w-full">Guardar compra</button></form></Modal>}</>;
}
